import Taro, { usePullDownRefresh } from '@tarojs/taro';
import { Input, Text, View } from '@tarojs/components';
import { QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import type { Asset, AssetKind } from 'shared';
import { coboardClient } from '../../platform/coboard-client';
import { useCurrentUser, useSessionToken } from '../../lib/auth';
import { ActionButton, Badge, Card, Empty, Field, PageHeader, Segmented, SelectField } from '../../components/ui';
import { StateView } from '../../components/StateView';
import { queryClient } from '../../lib/query';

type Filter = 'all' | AssetKind;
const labels: Record<AssetKind, string> = { content: '内容', feedback: '反馈', resource: '资源', issue: '问题' };
function AssetsPage(): JSX.Element {
  const token = useSessionToken(); const me = useCurrentUser(); const client = useQueryClient(); const [filter, setFilter] = useState<Filter>('all'); const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<Asset | null>(null); const [search, setSearch] = useState(''); const [kind, setKind] = useState<AssetKind>('content'); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [url, setUrl] = useState('');
  const query = useQuery({ queryKey: ['assets', filter, token], enabled: Boolean(token), queryFn: async () => (await coboardClient.assets.list(filter === 'all' ? {} : { kind: filter })).assets });
  const create = useMutation({ mutationFn: () => coboardClient.assets.create({ kind, title: title.trim(), body: body.trim() || undefined, url: url.trim() || undefined }), onSuccess: () => { setCreating(false); setTitle(''); setBody(''); setUrl(''); void client.invalidateQueries({ queryKey: ['assets'] }); } });
  const update = useMutation({ mutationFn: () => coboardClient.assets.update(editing!.id, { kind, title: title.trim(), body: body.trim(), url: url.trim() || null }), onSuccess: () => { setEditing(null); setTitle(''); setBody(''); setUrl(''); void client.invalidateQueries({ queryKey: ['assets'] }); } });
  const remove = useMutation({ mutationFn: (id: string) => coboardClient.assets.remove(id), onSuccess: () => void client.invalidateQueries({ queryKey: ['assets'] }) });
  const startEdit = (asset: Asset): void => { setCreating(false); setEditing(asset); setKind(asset.kind); setTitle(asset.title); setBody(asset.body); setUrl(asset.url ?? ''); };
  const confirmRemove = async (asset: Asset): Promise<void> => { const result = await Taro.showModal({ title: `删除“${asset.title}”？`, content: '删除后无法恢复。', confirmColor: '#dc2626' }); if (result.confirm) remove.mutate(asset.id); };
  usePullDownRefresh(async () => { await query.refetch(); Taro.stopPullDownRefresh(); });
  const kinds: AssetKind[] = ['content', 'feedback', 'resource', 'issue'];
  const term = search.trim().toLowerCase(); const visible = (query.data ?? []).filter((asset) => !term || asset.title.toLowerCase().includes(term) || asset.body.toLowerCase().includes(term)); const isAdmin = me.data?.role === 'admin' || me.data?.role === 'super_admin';
  return <View className="page"><PageHeader title="资产库" description="沉淀团队可复用的内容、反馈、资源和问题。" action={<ActionButton size="small" onClick={() => { if (creating || editing) { setCreating(false); setEditing(null); } else { setCreating(true); setTitle(''); setBody(''); setUrl(''); } }}>{creating || editing ? '取消' : '新建'}</ActionButton>} />{(creating || editing) && <Card className="stack"><Text className="title">{editing ? '编辑资产' : '新建资产'}</Text><SelectField label="类型" range={kinds.map((item) => labels[item])} value={kinds.indexOf(kind)} valueLabel={labels[kind]} onChange={(index) => setKind(kinds[index] ?? 'content')} /><Field label="标题" value={title} onChange={setTitle} /><Field label="正文" value={body} multiline onChange={setBody} /><Field label="链接（可选）" value={url} onChange={setUrl} /><ActionButton loading={create.isPending || update.isPending} disabled={!title.trim() || (!body.trim() && !url.trim())} onClick={() => editing ? update.mutate() : create.mutate()}>{editing ? '保存修改' : '保存资产'}</ActionButton></Card>}<View className="field__control"><Input value={search} placeholder="搜索标题或正文…" onInput={(event) => setSearch(event.detail.value)} /></View><Segmented value={filter} onChange={setFilter} items={[{ value: 'all', label: '全部' }, ...kinds.map((item) => ({ value: item, label: labels[item] }))]} /><StateView loading={query.isLoading} error={query.isError} empty={false} onRetry={() => void query.refetch()}>{visible.length === 0 ? <Empty title={term ? '没有匹配的资产' : '暂无资产'} /> : <View className="stack">{visible.map((asset) => <Card key={asset.id}><View className="stack"><View className="row-between"><Badge>{labels[asset.kind]}</Badge>{asset.trackName && <Text className="caption">{asset.trackName}</Text>}</View><Text className="title">{asset.title}</Text>{asset.body && <Text className="body muted">{asset.body}</Text>}{asset.url && <Text className="caption" onClick={() => void Taro.setClipboardData({ data: asset.url! })}>{asset.url} · 复制链接</Text>}<View className="row-between"><Text className="caption">创建人 {asset.creator.displayName}</Text>{(isAdmin || asset.creator.id === me.data?.id) && <View className="row"><ActionButton tone="ghost" size="small" onClick={() => startEdit(asset)}>编辑</ActionButton><ActionButton tone="danger" size="small" loading={remove.isPending} onClick={() => void confirmRemove(asset)}>删除</ActionButton></View>}</View></View></Card>)}</View>}</StateView></View>;
}
export default function AssetsPageRoot(): JSX.Element { return <QueryClientProvider client={queryClient}><AssetsPage /></QueryClientProvider>; }
