export default defineAppConfig({
  pages: [
    'pages/workbench/index',
    'pages/board/index',
    'pages/projects/index',
    'pages/notifications/index',
    'pages/more/index',
    'pages/ideas/index',
    'pages/assets/index',
    'pages/org/index',
    'pages/info/index',
    'pages/stats/index',
    'pages/profile/index',
    'pages/admin/index',
    'pages/auth-login/index',
    'pages/auth-callback/index',
    'pages/task/index',
  ],
  window: {
    navigationBarTitleText: 'Coboard',
    navigationBarBackgroundColor: '#fafaf9',
    navigationBarTextStyle: 'black',
    backgroundColor: '#fafaf9',
    backgroundTextStyle: 'dark',
  },
  tabBar: {
    color: '#626266',
    selectedColor: '#0d0d0e',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/board/index',
        text: '看板',
        iconPath: 'assets/tabbar/board-default.png',
        selectedIconPath: 'assets/tabbar/board-selected.png',
      },
      {
        pagePath: 'pages/workbench/index',
        text: '工作台',
        iconPath: 'assets/tabbar/workbench-default.png',
        selectedIconPath: 'assets/tabbar/workbench-selected.png',
      },
      {
        pagePath: 'pages/projects/index',
        text: '项目',
        iconPath: 'assets/tabbar/projects-default.png',
        selectedIconPath: 'assets/tabbar/projects-selected.png',
      },
      {
        pagePath: 'pages/notifications/index',
        text: '通知',
        iconPath: 'assets/tabbar/notifications-default.png',
        selectedIconPath: 'assets/tabbar/notifications-selected.png',
      },
      {
        pagePath: 'pages/more/index',
        text: '更多',
        iconPath: 'assets/tabbar/more-default.png',
        selectedIconPath: 'assets/tabbar/more-selected.png',
      },
    ],
  },
  networkTimeout: { request: 20000, uploadFile: 60000, downloadFile: 60000 },
});
